export const HADA_VERB_ENDING = 'HADA_VERB_ENDING';
export const AO_WITH_FINAL_VERB_ENDING = 'AO_WITH_FINAL_VERB_ENDING';
export const A_WITHOUT_FINAL_VERB_ENDING = 'A_WITHOUT_FINAL_VERB_ENDING';
export const O_WITHOUT_FINAL_VERB_ENDING = 'O_WITHOUT_FINAL_VERB_ENDING';
export const I_WITHOUT_FINAL_VERB_ENDING = 'I_WITHOUT_FINAL_VERB_ENDING';
export const DEFAULT_WITH_FINAL_VERB_ENDING = 'DEFAULT_WITH_FINAL_VERB_ENDING';
export const DEFAULT_WITHOUT_FINAL_VERB_ENDING = 'DEFAULT_WITHOUT_FINAL_VERB_ENDING';